AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/*'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Layout/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
