name: 'Performance'

on:
  check_run:
    types: [completed]
  check_suite:
    types: [completed]
  status:
  pull_request:
  push:

jobs:
  lighthouse:
    # if: "contains(github.actor, 'netlify[bot]')"
    name: 'Lighthouse'
    runs-on: ubuntu-latest
    steps:
      - name: Output Event Details
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event }}
      - name: Output ENVs
        run: |
          printenv
